name: Run SonarQube with Maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pratikshatiwari_EmployeeService
     # mvn -B verify sonar:sonar -X -Dsonar.projectKey=pratikshatiwari_EmployeeService -Dsonar.organization=pratikshatiwari -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GIT_HUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
